import{loadData}from'./data-loader.js';import{validateData}from'./data-validator.js?v=20260721-minor-tweak-1';import{initialState,PHASES,transition,validateState}from'./state.js';import{saveGame,loadGame,deleteGame}from'./storage.js';import{createRng,createGameId,randomKey}from'./random.js';import{POSITIONS,makeId,slugify,delay,escapeHTML}from'./utils.js';import{welcomeView,setupView,nameFields}from'./setup.js';import{eligiblePlayers,ERA_OPTIONS,eligiblePlayersForEra,eligibleOpenPositions,availableEraOptions}from'./draft.js?v=20260721-minor-tweak-1';import{wheelView,playerListView,animateWheel}from'./wheel.js';import{playerDraftView,draftRosterView,selectedFranchiseBanner}from'./draft-board.js?v=20260721-minor-tweak-1';import{calculateTeamRatings}from'./ratings.js?v=20260721-minor-tweak-1';import{generateSchedule}from'./schedule.js';import{createStandings,applyGame}from'./standings.js';import{simulateGame}from'./simulator.js';import{seasonView}from'./season-ui.js';import{resultsView,resultsText}from'./results.js';import{openPostseason,renderQualificationScreen,renderPlayoffScreen}from'./playoff-controller.js';import{assignedPosition,lineupSnapshot,moveOrSwap,validateLineup}from'./lineup.js?v=20260721-minor-tweak-1';
const app=document.querySelector('#app'),announcer=document.querySelector('#announcer'),saveStatus=document.querySelector('#save-status'),errorPanel=document.querySelector('#error-panel');let data,state;
function showError(message){errorPanel.textContent=message;errorPanel.hidden=false;setTimeout(()=>errorPanel.hidden=true,7000)}
function save(){if(saveGame(state)){saveStatus.textContent='Saved just now'}else showError('The browser could not save this game. You can keep playing, but progress may not survive a reload.')}
function setState(next){state=next;render()}
function fresh(){return initialState(createGameId())}
function bindGlobal(){document.querySelector('#sound-toggle').onclick=()=>{state.settings.sound=!state.settings.sound;document.querySelector('#sound-toggle').textContent=`Sound ${state.settings.sound?'on':'off'}`;save()};document.querySelector('#restart-button').onclick=()=>{if(confirm('Start an entirely new game? Saved draft and season progress will be deleted.')){deleteGame();setState(fresh())}}}
function render(){document.body.classList.toggle('reduced-motion',state.settings.reducedMotion);document.querySelector('#sound-toggle').textContent=`Sound ${state.settings.sound?'on':'off'}`;if(state.phase===PHASES.WELCOME)renderWelcome();else if(state.phase===PHASES.SETUP)renderSetup();else if(state.phase===PHASES.DRAFT)renderDraftV3();else if(state.phase===PHASES.LINEUP)resumeLegacyLineupPhase();else if(state.phase===PHASES.REVIEW)renderReview();else if(state.phase===PHASES.SEASON)renderSeason();else if(state.phase===PHASES.POSTSEASON_QUALIFICATION)renderQualificationScreen(state,{save,render,showError});else if(state.phase===PHASES.PLAYOFF_BRACKET||state.phase===PHASES.PLAYOFF_ROUND_RESULTS||state.phase===PHASES.PLAYOFF_COMPLETE)renderPlayoffScreen(state,{save,render,showError,announcer});else if(state.phase===PHASES.FINAL)renderFinal();bindGlobal();window.scrollTo({top:0,behavior:state.settings.reducedMotion?'auto':'smooth'})}
function renderWelcome(){const saved=loadGame();app.innerHTML=welcomeView(Boolean(saved),data.version);document.querySelector('#start').onclick=()=>setState({...fresh(),phase:PHASES.SETUP});document.querySelector('#resume')?.addEventListener('click',()=>{if(saved&&validateState(saved))setState(saved);else showError('That saved game is incompatible or corrupt. Start a new game instead.')})}
function renderSetup(){app.innerHTML=setupView();const count=document.querySelector('#user-count'),names=document.querySelector('#names');const update=()=>{const values=[...names.querySelectorAll('.card')].map(card=>({name:card.querySelector('[name=user-name]')?.value,teamName:card.querySelector('[name=team-name]')?.value}));names.innerHTML=nameFields(Number(count.value),values);names.querySelectorAll('[name=user-name]').forEach((input,i)=>input.addEventListener('input',()=>{const team=names.querySelectorAll('[name=team-name]')[i];if(!team.dataset.edited)team.value=`${input.value.trim()}'s Legends`}));names.querySelectorAll('[name=team-name]').forEach(input=>input.addEventListener('input',()=>input.dataset.edited='1'))};update();count.onchange=update;document.querySelector('#setup-form').onsubmit=event=>{event.preventDefault();const userNames=[...document.querySelectorAll('[name=user-name]')].map(i=>i.value.trim()),teamNames=[...document.querySelectorAll('[name=team-name]')].map(i=>i.value.trim());if(userNames.some(n=>!n)||new Set(userNames.map(n=>n.toLowerCase())).size!==userNames.length)return showError('Every player needs a unique name.');if(teamNames.some(n=>!n)||new Set(teamNames.map(n=>n.toLowerCase())).size!==teamNames.length)return showError('Every custom team needs a unique name.');const used=new Set();state.settings.strictUniqueness=document.querySelector('#strict').checked;state.settings.reducedMotion=document.querySelector('#reduced').checked;state.settings.speed=document.querySelector('#speed').value.toLowerCase();state.users=userNames.map(escapeHTML);state.customTeams=userNames.map((owner,i)=>({id:makeId(`custom-${slugify(teamNames[i])}`,used),name:escapeHTML(teamNames[i]),owner:escapeHTML(owner),roster:[],custom:true,theme:{primary:['#17408B','#C9082A','#17408B','#C9082A','#17408B','#C9082A','#17408B','#C9082A'][i],secondary:'#ffffff'}}));transition(state,PHASES.DRAFT);save();render()}}
function allDrafted(){return state.customTeams.flatMap(team=>team.roster)}
function renderDraftV3(){
  const team=state.customTeams[state.draft.teamIndex],stage=state.draft.stage,pick=team.roster.length+1;
  const franchise=data.teamsById.get(state.draft.franchiseId),era=ERA_OPTIONS.find(item=>item.id===state.draft.era);
  const fullPool=stage==='player'?eligiblePlayersForEra(data,{teamId:state.draft.franchiseId,eraId:state.draft.era,roster:team.roster,allDrafted:allDrafted(),strictUniqueness:state.settings.strictUniqueness}):[];
  const pool=fullPool.map(player=>({...player,eligibleOpenPositions:eligibleOpenPositions(player,team.roster)}));
  let selected=stage==='player'&&activeDraftPlayerId?data.playersById.get(activeDraftPlayerId):null;
  let selectedOpen=selected?eligibleOpenPositions(selected,team.roster):[];
  if(selected&&!fullPool.some(player=>player.id===selected.id)||selected&&!selectedOpen.length){activeDraftPlayerId=null;selected=null;selectedOpen=[]}
  const wheelItems=stage==='franchise'?data.teams.filter(item=>item.active):ERA_OPTIONS;
  const main=stage==='player'
    ?playerDraftView({players:pool,selectedId:selected?.id,eraName:era?.name||state.draft.era,franchiseName:franchise?.name||state.draft.franchiseId})
    :`${selectedFranchiseBanner(stage,franchise?.name)}${wheelView({title:stage==='franchise'?'Franchise wheel':'Era wheel',subtitle:stage==='franchise'?'Spin all 30 franchises':'Spin across basketball history',result:state.draft.result,items:wheelItems,canContinue:Boolean(state.draft.result)})}`;
  app.innerHTML=`<div class="screen-head"><div><p class="eyebrow">${team.owner}'s draft · Pick ${pick} of 5</p><h2>${team.name}</h2></div><div><span class="pill active">Draft Pick ${pick}</span> <span class="pill">${stage==='player'?'Choose any player':stage==='era'?'Choose an era':'Choose a franchise'}</span></div></div><div class="draft-layout">${main}<aside class="stack">${draftRosterView(team,selected)}<div class="card draft-history"><h3>Draft trail</h3>${state.draft.history.slice(-10).reverse().map(item=>`<p class="muted">${item}</p>`).join('')||'<p class="muted">Your selections appear here.</p>'}</div></aside></div>`;
  const wheel=document.querySelector('#wheel');
  wheel?.addEventListener('click',spinV3);
  wheel?.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();spinV3()}});
  document.querySelector('#continue-draft')?.addEventListener('click',continueDraftV3);
  document.querySelectorAll('.player-card:not(:disabled)').forEach(card=>card.addEventListener('click',()=>selectDraftPlayer(team,card.dataset.playerId)));
  bindDraftLineup(team);
}
function selectDraftPlayer(team,playerId){const player=data.playersById.get(playerId),eligible=player?eligibleOpenPositions(player,team.roster):[];if(!player||!eligible.length)return;activeDraftPlayerId=playerId;render();announcer.textContent=`${player.name} selected. Choose ${eligible.join(' or ')} to complete the pick.`}
async function spinV3(){
  if(wheelSpinning||state.draft.result||state.draft.stage==='player')return;
  wheelSpinning=true;
  const team=state.customTeams[state.draft.teamIndex];
  const available=state.draft.stage==='franchise'?data.teams.filter(item=>item.active):availableEraOptions(data,{teamId:state.draft.franchiseId,roster:team.roster,allDrafted:allDrafted(),strictUniqueness:state.settings.strictUniqueness});
  if(!available.length){wheelSpinning=false;showError('No eligible choices remain. Your completed roster picks are preserved.');return}
  const eventRng=createRng(randomKey(state.gameId,"DRAFT",team.id,team.roster.length+1,state.draft.stage)),selected=available[eventRng.int(available.length)],wheelItems=state.draft.stage==='franchise'?data.teams.filter(item=>item.active):ERA_OPTIONS,index=wheelItems.findIndex(item=>item.id===selected.id);
  try{await animateWheel({index},state.settings,wheelItems.length);state.draft.result={...selected,index};announcer.textContent=`${stageLabel()} wheel selected ${selected.name}. Continue when ready.`}finally{wheelSpinning=false}
  render();
}
function continueDraftV3(){
  if(!state.draft.result)return;
  const team=state.customTeams[state.draft.teamIndex],result=state.draft.result;
  if(state.draft.stage==='franchise'){state.draft.franchiseId=result.id;state.draft.history.push(`Franchise: ${result.name}`);state.draft.stage='era'}
  else if(state.draft.stage==='era'){state.draft.era=result.id;state.draft.history.push(`Era: ${result.name}`);state.draft.stage='player'}
  state.draft.result=null;render();
}
function placeDraftPlayer(playerId,position){
  const team=state.customTeams[state.draft.teamIndex],player=data.playersById.get(playerId),pickNumber=team.roster.length+1;
  if(!player||team.roster.some(slot=>slot.player.id===playerId)||team.roster.some(slot=>assignedPosition(slot)===position)||!player.positions.includes(position)){announceDraftLineup(`${player?.name||'That player'} cannot be placed at ${position}. Choose an eligible open position.`);return}
  team.roster.push({player,initialAssignedPosition:position,assignedPosition:position,draftPickNumber:pickNumber,draftOrder:pickNumber});state.draft.history.push(`Pick ${pickNumber}: ${player.name} placed at ${position}`);state.draft.pickNumber=pickNumber+1;state.draft.stage='franchise';state.draft.franchiseId=null;state.draft.era=null;state.draft.result=null;activeDraftPlayerId=null;state.draft.failed=[];
  if(team.roster.length===5){const validation=validateLineup(team.roster,data.playersById);if(!validation.valid){announceDraftLineup(validation.errors[0].message);return}team.lineupConfirmed=true;team.lastValidLineup=lineupSnapshot(team.roster);Object.assign(team,calculateTeamRatings(team.roster));state.draft.teamIndex++;state.draft.pickNumber=1;if(state.draft.teamIndex===state.customTeams.length)transition(state,PHASES.REVIEW)}
  save();
  render();
  announcer.textContent=`Drafted ${player.name} at ${position}.`;
}

function announceDraftLineup(message){announcer.textContent=message;document.querySelector('#draft-lineup-feedback')?.replaceChildren(document.createTextNode(message))}
function applyDraftLineupChange(team,playerId,targetPosition){const result=moveOrSwap(team.roster,playerId,targetPosition);if(!result.success||!result.changed){announceDraftLineup(result.message);return}team.roster=result.roster;if(team.roster.length===5&&validateLineup(team.roster,data.playersById).valid){team.lastValidLineup=lineupSnapshot(team.roster);Object.assign(team,calculateTeamRatings(team.roster))}save();render();announceDraftLineup(result.message)}
function bindDraftLineup(team){let draggedId=null;const slots=[...document.querySelectorAll('.draft-lineup-slot')],clear=()=>{draggedId=null;slots.forEach(slot=>{slot.classList.remove('drop-valid','drop-invalid');slot.querySelector('.drop-status')?.replaceChildren(document.createTextNode(slot.classList.contains('filled')?'Occupied':'Unavailable'))})};document.querySelectorAll('[data-drafted-player-id]').forEach(player=>{player.addEventListener('dragstart',event=>{draggedId=player.dataset.draftedPlayerId;event.dataTransfer.setData('application/x-drafted-player',draggedId);event.dataTransfer.effectAllowed='move';slots.forEach(slot=>{const result=moveOrSwap(team.roster,draggedId,slot.dataset.position),valid=result.success&&result.changed;slot.classList.add(valid?'drop-valid':'drop-invalid');slot.querySelector('.drop-status')?.replaceChildren(document.createTextNode(valid?'Allowed':'Not allowed'))})});player.addEventListener('dragend',clear)});slots.forEach(slot=>{slot.addEventListener('dragover',event=>{if(draggedId&&moveOrSwap(team.roster,draggedId,slot.dataset.position).success){event.preventDefault();event.dataTransfer.dropEffect='move'}});slot.addEventListener('drop',event=>{event.preventDefault();const rosterId=draggedId||event.dataTransfer.getData('application/x-drafted-player');if(rosterId)applyDraftLineupChange(team,rosterId,slot.dataset.position);clear()});slot.addEventListener('click',event=>{if(event.target.closest('[data-drafted-player-id]'))return;if(!activeDraftPlayerId)return;const player=data.playersById.get(activeDraftPlayerId),position=slot.dataset.position,occupied=team.roster.some(item=>assignedPosition(item)===position);if(!player||occupied||!player.positions.includes(position)){announceDraftLineup('This player cannot be placed here.');return}placeDraftPlayer(activeDraftPlayerId,position)});slot.addEventListener('keydown',event=>{if(event.key!=='Enter'&&event.key!==' ')return;if(!slot.classList.contains('draft-target')){announceDraftLineup('This player cannot be placed here.');return}event.preventDefault();placeDraftPlayer(activeDraftPlayerId,slot.dataset.position)})})}

function resumeLegacyLineupPhase(){const team=state.customTeams.find(item=>item.id===state.lineup?.teamId)||state.customTeams[state.draft.teamIndex];if(team&&validateLineup(team.roster,data.playersById).valid){team.lineupConfirmed=true;team.lastValidLineup=lineupSnapshot(team.roster);Object.assign(team,calculateTeamRatings(team.roster));if(state.draft.teamIndex<state.customTeams.length&&state.customTeams[state.draft.teamIndex]?.id===team.id)state.draft.teamIndex++;state.lineup=null;transition(state,state.draft.teamIndex>=state.customTeams.length?PHASES.REVIEW:PHASES.DRAFT);save();render()}else{state.lineup=null;transition(state,PHASES.DRAFT);save();render()}}
let wheelSpinning=false,activeDraftPlayerId=null;
function stageLabel(){return state.draft.stage[0].toUpperCase()+state.draft.stage.slice(1)}
function renderReview(){state.customTeams.forEach((team,i)=>{team.conference=i%2===0?'East':'West';team.division='Expansion';Object.assign(team,calculateTeamRatings(team.roster))});app.innerHTML=`<div class="screen-head"><div><p class="eyebrow">Draft and lineups complete</p><h1>Meet the<br><em>expansion</em></h1></div><span class="pill">Lineups set during draft</span></div><div class="grid grid-2">${state.customTeams.map(team=>`<article class="card team-accent" style="--accent:${team.theme.primary}"><div class="split"><div><h2>${team.name}</h2><p class="muted">${team.owner} · ${team.conference} Conference</p></div><span class="rating">${team.overall}</span></div>${[...team.roster].sort((a,b)=>POSITIONS.indexOf(assignedPosition(a))-POSITIONS.indexOf(assignedPosition(b))).map(slot=>`<div class="roster-slot review-lineup-slot"><span class="position">${assignedPosition(slot)}</span><span><b>${slot.player.name}</b><small class="muted">${slot.player.teamId} · ${slot.player.era} · ${slot.player.season}</small><small class="muted">Eligible ${slot.player.positions.join('/')} · Pick ${slot.draftPickNumber} · Initially ${slot.initialAssignedPosition}${slot.initialAssignedPosition!==assignedPosition(slot)?` · Starting ${assignedPosition(slot)}`:''}</small></span><strong>${slot.player.overall}</strong></div>`).join('')}<div class="stat-strip"><div class="stat"><span>Offense</span><strong>${team.offense}</strong></div><div class="stat"><span>Defense</span><strong>${team.defense}</strong></div><div class="stat"><span>Chemistry</span><strong>${team.chemistry}</strong></div></div></article>`).join('')}</div><p class="shared-round-note">Lineups are locked after the draft.</p><div class="actions"><button class="button" id="create-league">Generate 82-game season</button></div>`;document.querySelector('#create-league').onclick=()=>{try{for(const team of state.customTeams){const validation=validateLineup(team.roster,data.playersById);if(!team.lineupConfirmed||!validation.valid)throw new Error(`${team.name} needs a valid lineup.`);team.lineupLocked=true;Object.assign(team,calculateTeamRatings(team.roster))}const base=data.teams.filter(team=>team.active).map(team=>({...team,overall:team.baseOverall,offense:team.baseOffense,defense:team.baseDefense,custom:false}));state.league=[...base,...state.customTeams];state.schedule=generateSchedule(state.league,state.gameId);state.standings=createStandings(state.league);state.season={gameIndex:0,currentDay:0,running:false,latest:[]};transition(state,PHASES.SEASON);save();render()}catch(error){console.error(error);showError(error.message||'Schedule generation failed. Your completed draft is preserved; please retry.')}}}
function renderSeason(){app.innerHTML=seasonView(state);document.querySelector('#sim-game')?.addEventListener('click',()=>runSimulation('game'));document.querySelector('#sim-day')?.addEventListener('click',()=>runSimulation('day'));document.querySelector('#sim-season')?.addEventListener('click',()=>runSimulation('season'));document.querySelector('#pause')?.addEventListener('click',()=>{state.season.running=false;render()});document.querySelector('#season-speed')?.addEventListener('change',e=>{state.settings.speed=e.target.value.toLowerCase();save()});document.querySelector('#view-results')?.addEventListener('click',()=>{openPostseason(state,{save,render,showError})})}
function simulateNext(){const game=state.schedule[state.season.gameIndex];if(!game)return null;const teamMap=new Map(state.league.map(t=>[t.id,t])),gameRng=createRng(randomKey(state.gameId,"REGULAR",game.id)),played=simulateGame(game,teamMap,gameRng);state.schedule[state.season.gameIndex]=played;applyGame(state.standings,played);state.season.gameIndex++;state.season.currentDay=played.day;state.season.latest=[played,...state.season.latest].slice(0,10);return played}
async function runSimulation(mode){if(state.season.running)return;state.season.running=true;const firstDay=state.schedule[state.season.gameIndex]?.day;while(state.season.running&&state.season.gameIndex<state.schedule.length){simulateNext();if(mode==='game'||(mode==='day'&&state.schedule[state.season.gameIndex]?.day!==firstDay))break;if(mode==='season'&&state.season.gameIndex%30===0){renderSeason();await delay({slow:120,normal:45,fast:12,instant:0}[state.settings.speed])}}state.season.running=false;save();render();announcer.textContent=`${state.season.gameIndex} of ${state.schedule.length} games complete.`}
function renderFinal(){app.innerHTML=resultsView(state);document.querySelectorAll('.copy-result').forEach(button=>button.onclick=async()=>{const team=state.customTeams.find(t=>t.id===button.dataset.team);await navigator.clipboard.writeText(resultsText(team,state));button.textContent='Copied'});document.querySelector('#restart-season-same-draft').onclick=()=>{if(confirm('Restart the season with the same drafted teams? This creates fresh outcomes.')){state.gameId=createGameId();state.playoffs=null;state.schedule=generateSchedule(state.league,state.gameId);state.standings=createStandings(state.league);state.season={gameIndex:0,currentDay:0,running:false,latest:[]};transition(state,PHASES.SEASON);save();render()}};document.querySelector('#new-game-final').onclick=()=>{deleteGame();setState(fresh())}}
async function boot(){try{data=await loadData();const validation=validateData(data);if(!validation.valid)throw new Error(validation.errors.join('\n'));if(validation.warnings.length)console.warn('Data warnings',validation.warnings);state=fresh();render()}catch(error){console.error(error);app.innerHTML='<section class="card"><p class="eyebrow">Loading error</p><h2>The local game data could not be loaded.</h2><p class="lede">Run the project through a local web server and retry. No saved draft data was changed.</p><button class="button" onclick="location.reload()">Retry</button></section>'}}boot();
