import{POSITIONS}from'./utils.js';

const ratingKeys=[['offense','OFF'],['defense','DEF'],['shooting','SHT'],['playmaking','PLY'],['rebounding','REB'],['athleticism','ATH']];

export function playerDraftView({players,total=players.length,selectedId,eraName,franchiseName,filters={query:'',position:'ALL',sort:'overall'}}){
  return`<section class="card player-picker draft-pool"><div class="split"><div><p class="eyebrow">${franchiseName} · ${eraName}</p><h2>Choose any available player</h2></div><span class="pill">${players.length}/${total} shown</span></div><p class="muted player-picker-help">Click or tap a card, then click a highlighted open position to draft that player immediately.</p><div class="player-list-tools"><label>Search<input id="player-search" type="search" value="${filters.query}" placeholder="Player name"></label><label>Position<select id="player-position-filter"><option value="ALL">All positions</option>${POSITIONS.map(position=>`<option value="${position}" ${filters.position===position?'selected':''}>${position}</option>`).join('')}</select></label><label>Sort<select id="player-sort"><option value="overall" ${filters.sort==='overall'?'selected':''}>Overall</option><option value="name" ${filters.sort==='name'?'selected':''}>Alphabetical</option></select></label><button type="button" class="button ghost" id="clear-player-filters">Clear filters</button></div><div class="player-options expanded-player-options" aria-label="Available players">${players.map(player=>{const canFit=player.eligibleOpenPositions.length>0,selected=selectedId===player.id;return`<button type="button" class="player-option detailed-player player-card ${selected?'selected':''} ${canFit?'':'unavailable'}" data-player-id="${player.id}" aria-pressed="${selected}" ${canFit?'':'disabled'}><span class="player-card-state">${selected?'✓ Selected':canFit?'Select player':'Unavailable'}</span><span class="player-option-main"><span class="player-option-copy"><strong>${player.name}</strong><small>${franchiseName} · ${player.era==='all-time'?'All-Time':'Current'} · ${player.season}</small><small>Eligible positions: ${player.positions.join(', ')}</small><small>${canFit?`Can fill an open position: ${player.eligibleOpenPositions.join(', ')}`:'No eligible open position'}</small></span><span class="overall-badge"><small>OVR</small>${player.overall}</span></span><span class="attribute-row">${ratingKeys.map(([key,label])=>`<span><small>${label}</small><b>${player[key]}</b></span>`).join('')}</span></button>`}).join('')||'<p class="muted">No players match these filters.</p>'}</div></section>`
}

export function draftRosterView(team,selectedPlayer){
  const open=POSITIONS.filter(position=>!team.roster.some(item=>(item.assignedPosition||item.position)===position));
  return`<div class="card draft-lineup-card ${selectedPlayer?'has-selection':''}"><div class="split"><div><h3>Drafting lineup</h3><p class="muted">Positions still needed: ${open.join(', ')||'None'}</p></div><span class="pill">${team.roster.length}/5</span></div><div class="draft-dropzones" role="list" aria-label="Drafted starting lineup">${POSITIONS.map(position=>{const slot=team.roster.find(item=>(item.assignedPosition||item.position)===position),draftTarget=Boolean(selectedPlayer)&&!slot&&selectedPlayer.positions.includes(position);return`<div class="roster-slot drop-slot draft-lineup-slot ${slot?'filled':''} ${draftTarget?'eligible draft-target':''}" data-position="${position}" role="listitem" ${draftTarget?'tabindex="0" aria-label="Draft '+selectedPlayer.name+' at '+position+'"':''}><span class="position">${position}</span>${slot?`<span class="drafted-player-copy" draggable="true" data-drafted-player-id="${slot.player.id}" tabindex="0"><b><span class="drag-handle" aria-hidden="true">↕</span> ${slot.player.name}</b><small>Eligible: ${slot.player.positions.join(', ')}</small><small>Overall: ${slot.player.overall} · Pick ${slot.draftPickNumber||slot.draftOrder}</small></span><span class="drop-status" aria-hidden="true">Occupied</span><div class="draft-move-control"><label><span class="sr-only">Move ${slot.player.name} to position</span><select class="draft-position-select" data-player-id="${slot.player.id}" aria-label="Move ${slot.player.name} to position">${POSITIONS.filter(option=>slot.player.positions.includes(option)).map(option=>`<option value="${option}" ${option===position?'selected':''}>${option}</option>`).join('')}</select></label><button type="button" class="icon-button draft-move-button" data-player-id="${slot.player.id}">Move</button></div>`:`<span><b>${draftTarget?`Draft ${selectedPlayer.name} here`:'Empty'}</b><small class="muted">${draftTarget?'Click to place immediately':selectedPlayer?'This player cannot play here':'Available for an eligible player'}</small></span><span class="drop-status" aria-hidden="true">${draftTarget?'Eligible':'Unavailable'}</span>`}</div>`}).join('')}</div><div id="draft-lineup-feedback" class="lineup-feedback compact" role="status" aria-live="polite">${selectedPlayer?`Selected ${selectedPlayer.name}. Click a highlighted open position to complete the pick.`:'Click or tap an available player card to begin.'}</div></div>`
}
