import{POSITIONS}from'./utils.js';

export const assignedPosition=entry=>entry.assignedPosition||entry.initialAssignedPosition||entry.position||entry.draftedForPosition;
export const draftedPosition=entry=>entry.initialAssignedPosition||entry.draftedForPosition||entry.position||entry.assignedPosition;

export function normalizeRoster(roster=[]){return roster.map((entry,index)=>({...entry,initialAssignedPosition:draftedPosition(entry),assignedPosition:assignedPosition(entry),draftPickNumber:entry.draftPickNumber||entry.draftOrder||index+1,draftOrder:entry.draftOrder||entry.draftPickNumber||index+1}))}

function error(code,message,entry={}){return{code,message,playerId:entry.player?.id||entry.playerId||null,assignedPosition:assignedPosition(entry)||null}}

export function validateLineup(roster=[],playersById=null){const entries=normalizeRoster(roster),errors=[],positions=entries.map(assignedPosition),ids=entries.map(entry=>entry.player?.id||entry.playerId).filter(Boolean);if(entries.length!==5)errors.push(error('INVALID_ROSTER_SIZE','A starting lineup must contain exactly five players.'));for(const entry of entries){const id=entry.player?.id||entry.playerId,player=entry.player||playersById?.get?.(id);if(!id||!player)errors.push(error('UNKNOWN_PLAYER','A lineup entry references an unknown player.',entry));const position=assignedPosition(entry);if(!POSITIONS.includes(position))errors.push(error('UNKNOWN_POSITION',`${position||'An empty position'} is not a valid starting position.`,entry));else if(player&&!player.positions?.includes(position))errors.push(error('INELIGIBLE_POSITION',`${player.name} is not eligible to play ${position}.`,entry))}for(const position of POSITIONS){const count=positions.filter(value=>value===position).length;if(count===0)errors.push(error('MISSING_POSITION',`${position} is missing from the starting lineup.`,{assignedPosition:position}));if(count>1)errors.push(error('DUPLICATE_POSITION',`${position} is assigned more than once.`,{assignedPosition:position}))}if(new Set(ids).size!==ids.length)errors.push(error('DUPLICATE_PLAYER','A player appears more than once in the starting lineup.'));return{valid:errors.length===0,errors}}

export function validateDraftArrangement(roster=[],playersById=null){const entries=normalizeRoster(roster),errors=[],positions=entries.map(assignedPosition),ids=entries.map(entry=>entry.player?.id||entry.playerId).filter(Boolean);if(entries.length>5)errors.push(error('INVALID_ROSTER_SIZE','A draft lineup cannot contain more than five players.'));for(const entry of entries){const id=entry.player?.id||entry.playerId,player=entry.player||playersById?.get?.(id),position=assignedPosition(entry);if(!id||!player)errors.push(error('UNKNOWN_PLAYER','A lineup entry references an unknown player.',entry));if(!POSITIONS.includes(position))errors.push(error('UNKNOWN_POSITION',`${position||'An empty position'} is not a valid starting position.`,entry));else if(player&&!player.positions?.includes(position))errors.push(error('INELIGIBLE_POSITION',`${player.name} is not eligible to play ${position}.`,entry))}for(const position of POSITIONS)if(positions.filter(value=>value===position).length>1)errors.push(error('DUPLICATE_POSITION',`${position} is assigned more than once.`,{assignedPosition:position}));if(new Set(ids).size!==ids.length)errors.push(error('DUPLICATE_PLAYER','A player appears more than once in the lineup.'));return{valid:errors.length===0,errors}}

export const lineupSnapshot=roster=>normalizeRoster(roster).map(entry=>({playerId:entry.player?.id||entry.playerId,assignedPosition:entry.assignedPosition}));
export function restoreSnapshot(roster,snapshot){const assignments=new Map(snapshot.map(item=>[item.playerId,item.assignedPosition]));return normalizeRoster(roster).map(entry=>({...entry,assignedPosition:assignments.get(entry.player?.id||entry.playerId)||entry.assignedPosition}))}

export function moveOrSwap(roster,playerId,targetPosition){const current=normalizeRoster(roster),source=current.find(entry=>(entry.player?.id||entry.playerId)===playerId);if(!source)return{success:false,roster,message:'That player is not in this lineup.',error:{code:'UNKNOWN_PLAYER'}};if(!POSITIONS.includes(targetPosition))return{success:false,roster,message:`${targetPosition} is not a valid position.`,error:{code:'UNKNOWN_POSITION'}};const from=source.assignedPosition;if(from===targetPosition)return{success:true,changed:false,roster:current,message:`${source.player.name} is already starting at ${targetPosition}.`};const destination=current.find(entry=>entry.assignedPosition===targetPosition);if(!source.player.positions.includes(targetPosition))return{success:false,roster,message:`This ${destination?'swap':'move'} is not allowed because ${source.player.name} cannot play ${targetPosition}.`,error:{code:'INELIGIBLE_POSITION',playerId,targetPosition}};if(destination&&!destination.player.positions.includes(from))return{success:false,roster,message:`This swap is not allowed because ${destination.player.name} cannot play ${from}.`,error:{code:'INVALID_SWAP',playerId:destination.player.id,targetPosition:from}};const next=current.map(entry=>{const id=entry.player?.id||entry.playerId;if(id===playerId)return{...entry,assignedPosition:targetPosition};if(destination&&id===(destination.player?.id||destination.playerId))return{...entry,assignedPosition:from};return entry});const validation=next.length===5?validateLineup(next):validateDraftArrangement(next);if(!validation.valid)return{success:false,roster,message:validation.errors[0].message,error:validation.errors[0]};return{success:true,changed:true,roster:next,message:destination?`${source.player.name} and ${destination.player.name} swapped positions.`:`${source.player.name} moved from ${from} to ${targetPosition}.`}}

export function resetToDraftedPositions(roster){const next=normalizeRoster(roster).map(entry=>({...entry,assignedPosition:entry.initialAssignedPosition}));return{roster:next,validation:validateLineup(next)}}

export function isLineupEditable(phase){return phase==='DRAFT'}
