import{createSeries,simulateSeries,validateSeries}from'./playoff-series.js';

export const PLAYOFF_ROUNDS=['FIRST_ROUND','SEMIFINALS','CONFERENCE_FINALS','FINALS'];
export const ROUND_LABELS={FIRST_ROUND:'Conference First Round',SEMIFINALS:'Conference Semifinals',CONFERENCE_FINALS:'Conference Finals',FINALS:'NBA Finals'};
const pairings=[[1,8],[4,5],[2,7],[3,6]];
const slugRound={FIRST_ROUND:'r1',SEMIFINALS:'sf',CONFERENCE_FINALS:'cf',FINALS:'finals'};
function seedMap(entries){return new Map(entries.filter(item=>item.qualified).map(item=>[item.seed,item.teamId]))}
function firstRound(conference,entries){const map=seedMap(entries),key=conference.toLowerCase();return pairings.map(([a,b])=>createSeries({id:`playoff-${key}-r1-${a}v${b}`,conference,round:'FIRST_ROUND',teamAId:map.get(a),teamBId:map.get(b),teamASeed:a,teamBSeed:b,homeCourtTeamId:map.get(a)}))}

export function createPlayoffState(seeding,customTeams){const first=[...firstRound('East',seeding.East),...firstRound('West',seeding.West)],seriesById=Object.fromEntries(first.map(series=>[series.id,series]));const customStatus=Object.fromEntries(customTeams.map(team=>{const seed=seeding[team.conference].find(item=>item.teamId===team.id);return[team.id,{teamId:team.id,seed:seed.seed,status:seed.qualified?'ACTIVE_FIRST_ROUND':'NOT_QUALIFIED',seriesResults:[],playoffWins:0,playoffLosses:0}]}));return{enabled:true,entered:false,currentRound:'FIRST_ROUND',status:'QUALIFICATION',featuredCustomTeamId:null,seeding,roundSeriesIds:{FIRST_ROUND:first.map(series=>series.id),SEMIFINALS:[],CONFERENCE_FINALS:[],FINALS:[]},seriesById,completedRounds:[],championTeamId:null,customStatus}}
function regularRank(teamId,playoffs){for(const conference of['East','West']){const item=playoffs.seeding[conference].find(entry=>entry.teamId===teamId);if(item)return item}return null}
function nextSeries(playoffs,round,conference,winners,index,standings){const ids=winners.slice(index*2,index*2+2),entries=ids.map(id=>regularRank(id,playoffs)),a=entries[0],b=entries[1];let home=a.seed<b.seed?a.teamId:b.teamId;if(round==='FINALS'){if(a.record.wins!==b.record.wins)home=a.record.wins>b.record.wins?a.teamId:b.teamId;else if(a.record.pointDifferential!==b.record.pointDifferential)home=a.record.pointDifferential>b.record.pointDifferential?a.teamId:b.teamId;else if(a.record.pointsFor!==b.record.pointsFor)home=a.record.pointsFor>b.record.pointsFor?a.teamId:b.teamId;else home=a.seed<b.seed?a.teamId:b.teamId}return createSeries({id:`playoff-${conference.toLowerCase()}-${slugRound[round]}-${index+1}`,conference,round,teamAId:ids[0],teamBId:ids[1],teamASeed:a.seed,teamBSeed:b.seed,homeCourtTeamId:home})}
export function advanceBracket(playoffs,completedRound,standings){const ids=playoffs.roundSeriesIds[completedRound],series=ids.map(id=>playoffs.seriesById[id]);if(completedRound==='FIRST_ROUND'){for(const conference of['East','West']){const winners=series.filter(s=>s.conference===conference).map(s=>s.winnerTeamId);const next=[nextSeries(playoffs,'SEMIFINALS',conference,winners,0,standings),nextSeries(playoffs,'SEMIFINALS',conference,winners,1,standings)];next.forEach(s=>playoffs.seriesById[s.id]=s);playoffs.roundSeriesIds.SEMIFINALS.push(...next.map(s=>s.id))}playoffs.currentRound='SEMIFINALS'}else if(completedRound==='SEMIFINALS'){for(const conference of['East','West']){const winners=series.filter(s=>s.conference===conference).map(s=>s.winnerTeamId),next=nextSeries(playoffs,'CONFERENCE_FINALS',conference,winners,0,standings);playoffs.seriesById[next.id]=next;playoffs.roundSeriesIds.CONFERENCE_FINALS.push(next.id)}playoffs.currentRound='CONFERENCE_FINALS'}else if(completedRound==='CONFERENCE_FINALS'){const east=series.find(s=>s.conference==='East').winnerTeamId,west=series.find(s=>s.conference==='West').winnerTeamId,next=nextSeries(playoffs,'FINALS','NBA',[east,west],0,standings);next.id='playoff-nba-finals';next.conference='NBA';playoffs.seriesById[next.id]=next;playoffs.roundSeriesIds.FINALS=[next.id];playoffs.currentRound='FINALS'}else{playoffs.championTeamId=series[0].winnerTeamId;playoffs.currentRound=null;playoffs.status='COMPLETE'}}
export function simulatePlayoffRound(playoffs,league,standings,gameId,featuredCustomTeamId=null,onProgress=()=>{}){const round=playoffs.currentRound;if(!round||playoffs.completedRounds.includes(round))throw new Error('This playoff round is already complete.');playoffs.featuredCustomTeamId=featuredCustomTeamId;playoffs.status='IN_PROGRESS';const teamMap=new Map(league.map(team=>[team.id,team])),ids=playoffs.roundSeriesIds[round];for(const id of ids){const series=simulateSeries(playoffs.seriesById[id],teamMap,gameId,onProgress),validation=validateSeries(series);if(!validation.valid)throw new Error(validation.errors.join(' '))}playoffs.completedRounds.push(round);updateCustomStatuses(playoffs,league,round);advanceBracket(playoffs,round,standings);if(playoffs.status!=='COMPLETE')playoffs.status='ROUND_COMPLETE';return playoffs}
function updateCustomStatuses(playoffs,league,round){for(const team of league.filter(item=>item.custom)){const status=playoffs.customStatus[team.id];if(!status||status.status==='NOT_QUALIFIED'||status.status.startsWith('ELIMINATED'))continue;const series=Object.values(playoffs.seriesById).find(item=>item.round===round&&(item.teamAId===team.id||item.teamBId===team.id));if(!series)continue;const won=series.winnerTeamId===team.id,teamWins=series.teamAId===team.id?series.teamAWins:series.teamBWins,losses=series.games.length-teamWins;status.playoffWins+=teamWins;status.playoffLosses+=losses;status.seriesResults.push({round,won,wins:teamWins,losses,opponentId:series.teamAId===team.id?series.teamBId:series.teamAId,seriesId:series.id});if(!won)status.status=`ELIMINATED_${round}`;else status.status=round==='FINALS'?'CHAMPION':`ACTIVE_${{FIRST_ROUND:'SEMIFINALS',SEMIFINALS:'CONFERENCE_FINALS',CONFERENCE_FINALS:'FINALS'}[round]}`}}
export function validateBracket(playoffs){const errors=[],ids=new Set();for(const series of Object.values(playoffs.seriesById)){if(ids.has(series.id))errors.push(`Duplicate series ${series.id}.`);ids.add(series.id);if(series.teamAId===series.teamBId)errors.push(`${series.id} contains one team twice.`);const result=validateSeries(series);errors.push(...result.errors)}for(const round of PLAYOFF_ROUNDS){const teams=[];for(const id of playoffs.roundSeriesIds[round]){const s=playoffs.seriesById[id];if(s)teams.push(s.teamAId,s.teamBId)}if(new Set(teams).size!==teams.length)errors.push(`A team appears twice in ${round}.`)}return{valid:errors.length===0,errors}}
