import{restoreSnapshot,validateLineup}from'./lineup.js';
const KEY='basketball-legends-save-v1';
export function saveGame(state){try{state.savedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));return true}catch(error){console.error('Save failed',error);return false}}
const migrateRoster=roster=>(roster||[]).map((entry,index)=>{const initialAssignedPosition=entry.initialAssignedPosition||entry.draftedForPosition||entry.position||entry.assignedPosition;return{...entry,initialAssignedPosition,assignedPosition:entry.assignedPosition||initialAssignedPosition,draftPickNumber:entry.draftPickNumber||entry.draftOrder||index+1,draftOrder:entry.draftOrder||entry.draftPickNumber||index+1}});
const migrateTeam=team=>{const roster=migrateRoster(team.roster);return{...team,roster,lineupConfirmed:team.lineupConfirmed??roster.length===5,lastValidLineup:team.lastValidLineup||roster.map(entry=>({playerId:entry.player?.id||entry.playerId,assignedPosition:entry.assignedPosition})),lineupHistory:team.lineupHistory||[]}};
export function migrateSave(parsed){if(!parsed)return parsed;let next=parsed;if(next.schemaVersion==='1.0.0'||next.schemaVersion==='2.0.0'){const{seed,...legacy}=next;next={...legacy,schemaVersion:'3.0.0',gameId:`legacy-${seed||next.savedAt||'save'}`,playoffs:next.playoffs||null}}if(next.schemaVersion==='3.0.0'||next.schemaVersion==='4.0.0'){const customTeams=(next.customTeams||[]).map(migrateTeam),byId=new Map(customTeams.map(team=>[team.id,team])),activeTeam=customTeams[next.draft?.teamIndex||0];return{...next,schemaVersion:'5.0.0',customTeams,league:(next.league||[]).map(team=>team.custom&&byId.has(team.id)?byId.get(team.id):team),draft:{teamIndex:next.draft?.teamIndex||0,pickNumber:(activeTeam?.roster.length||0)+1,stage:next.draft?.stage||'franchise',franchiseId:next.draft?.franchiseId||null,era:next.draft?.era||null,result:next.draft?.result||null,failed:next.draft?.failed||[],history:next.draft?.history||[],playerSearch:'',playerSort:'overall',playerPosition:'ALL'},lineup:null}}return next}
export function recoverLineups(state){const customTeams=(state.customTeams||[]).map(team=>{if(validateLineup(team.roster).valid||!team.lastValidLineup?.length)return team;const roster=restoreSnapshot(team.roster,team.lastValidLineup);return validateLineup(roster).valid?{...team,roster}:team}),byId=new Map(customTeams.map(team=>[team.id,team]));return{...state,customTeams,league:(state.league||[]).map(team=>team.custom&&byId.has(team.id)?byId.get(team.id):team)}}
export function loadGame(){try{const raw=localStorage.getItem(KEY);if(!raw)return null;const parsed=migrateSave(JSON.parse(raw));return parsed?.schemaVersion==='5.0.0'?recoverLineups(parsed):null}catch(error){console.error('Saved game is invalid',error);return null}}
export function deleteGame(){try{localStorage.removeItem(KEY);return true}catch{return false}}
export const hasSavedGame=()=>Boolean(loadGame());
