#!/usr/bin/env python3
"""Build the checked-in prototype JSON dataset. Maintainer utility only."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
TEAMS=[
('ATL','Atlanta Hawks','Atlanta','East','Southeast',80,82,78,100,'#E03A3E','#C1D32F'),('BOS','Boston Celtics','Boston','East','Atlantic',94,94,93,98,'#007A33','#BA9653'),('BKN','Brooklyn Nets','Brooklyn','East','Atlantic',73,75,72,99,'#222222','#FFFFFF'),('CHA','Charlotte Hornets','Charlotte','East','Southeast',75,77,73,101,'#1D1160','#00788C'),('CHI','Chicago Bulls','Chicago','East','Central',78,79,77,98,'#CE1141','#000000'),('CLE','Cleveland Cavaliers','Cleveland','East','Central',92,91,93,97,'#860038','#FDBB30'),('DAL','Dallas Mavericks','Dallas','West','Southwest',84,87,80,99,'#00538C','#B8C4CA'),('DEN','Denver Nuggets','Denver','West','Northwest',89,91,86,97,'#0E2240','#FEC524'),('DET','Detroit Pistons','Detroit','East','Central',83,82,84,100,'#C8102E','#1D42BA'),('GSW','Golden State Warriors','San Francisco','West','Pacific',84,87,81,102,'#1D428A','#FFC72C'),('HOU','Houston Rockets','Houston','West','Southwest',88,86,91,100,'#CE1141','#C4CED4'),('IND','Indiana Pacers','Indianapolis','East','Central',87,91,82,104,'#002D62','#FDBB30'),('LAC','LA Clippers','Los Angeles','West','Pacific',82,83,82,98,'#C8102E','#1D428A'),('LAL','Los Angeles Lakers','Los Angeles','West','Pacific',86,88,83,101,'#552583','#FDB927'),('MEM','Memphis Grizzlies','Memphis','West','Southwest',84,85,84,102,'#5D76A9','#12173F'),('MIA','Miami Heat','Miami','East','Southeast',82,81,84,96,'#98002E','#F9A01B'),('MIL','Milwaukee Bucks','Milwaukee','East','Central',86,88,84,100,'#00471B','#EEE1C6'),('MIN','Minnesota Timberwolves','Minneapolis','West','Northwest',88,86,91,98,'#0C2340','#78BE20'),('NOP','New Orleans Pelicans','New Orleans','West','Southwest',77,79,76,99,'#0C2340','#C8102E'),('NYK','New York Knicks','New York','East','Atlantic',91,92,90,96,'#006BB6','#F58426'),('OKC','Oklahoma City Thunder','Oklahoma City','West','Northwest',96,96,96,102,'#007AC1','#EF3B24'),('ORL','Orlando Magic','Orlando','East','Southeast',86,82,91,97,'#0077C0','#C4CED4'),('PHI','Philadelphia 76ers','Philadelphia','East','Atlantic',80,83,78,98,'#006BB6','#ED174C'),('PHX','Phoenix Suns','Phoenix','West','Pacific',81,84,78,99,'#1D1160','#E56020'),('POR','Portland Trail Blazers','Portland','West','Northwest',79,78,81,101,'#E03A3E','#000000'),('SAC','Sacramento Kings','Sacramento','West','Pacific',82,85,79,103,'#5A2D81','#63727A'),('SAS','San Antonio Spurs','San Antonio','West','Southwest',88,89,87,101,'#C4CED4','#000000'),('TOR','Toronto Raptors','Toronto','East','Atlantic',81,80,83,100,'#CE1141','#000000'),('UTA','Utah Jazz','Salt Lake City','West','Northwest',76,78,74,99,'#002B5C','#F9A01B'),('WAS','Washington Wizards','Washington','East','Southeast',72,74,71,103,'#002B5C','#E31837')]
CURRENT={
'ATL':['Trae Young','Dyson Daniels','Zaccharie Risacher','Jalen Johnson','Onyeka Okongwu'],'BOS':['Jrue Holiday','Derrick White','Jaylen Brown','Jayson Tatum','Kristaps Porzingis'],'BKN':['D’Angelo Russell','Cam Thomas','Ziaire Williams','Noah Clowney','Nic Claxton'],'CHA':['LaMelo Ball','Josh Green','Brandon Miller','Miles Bridges','Mark Williams'],'CHI':['Josh Giddey','Coby White','Matas Buzelis','Patrick Williams','Nikola Vucevic'],'CLE':['Darius Garland','Donovan Mitchell','Max Strus','Evan Mobley','Jarrett Allen'],'DAL':['Kyrie Irving','Klay Thompson','Naji Marshall','Anthony Davis','Dereck Lively II'],'DEN':['Jamal Murray','Christian Braun','Michael Porter Jr.','Aaron Gordon','Nikola Jokic'],'DET':['Cade Cunningham','Jaden Ivey','Ausar Thompson','Tobias Harris','Jalen Duren'],'GSW':['Stephen Curry','Brandin Podziemski','Jimmy Butler','Jonathan Kuminga','Draymond Green'],'HOU':['Fred VanVleet','Jalen Green','Amen Thompson','Jabari Smith Jr.','Alperen Sengun'],'IND':['Tyrese Haliburton','Bennedict Mathurin','Aaron Nesmith','Pascal Siakam','Myles Turner'],'LAC':['James Harden','Norman Powell','Kawhi Leonard','Derrick Jones Jr.','Ivica Zubac'],'LAL':['Luka Doncic','Austin Reaves','LeBron James','Rui Hachimura','Jaxson Hayes'],'MEM':['Ja Morant','Desmond Bane','Jaylen Wells','Jaren Jackson Jr.','Zach Edey'],'MIA':['Davion Mitchell','Tyler Herro','Andrew Wiggins','Bam Adebayo','Kel’el Ware'],'MIL':['Damian Lillard','Gary Trent Jr.','Kyle Kuzma','Giannis Antetokounmpo','Brook Lopez'],'MIN':['Mike Conley','Anthony Edwards','Jaden McDaniels','Julius Randle','Rudy Gobert'],'NOP':['Dejounte Murray','CJ McCollum','Trey Murphy III','Zion Williamson','Yves Missi'],'NYK':['Jalen Brunson','Mikal Bridges','OG Anunoby','Josh Hart','Karl-Anthony Towns'],'OKC':['Shai Gilgeous-Alexander','Luguentz Dort','Jalen Williams','Chet Holmgren','Isaiah Hartenstein'],'ORL':['Jalen Suggs','Kentavious Caldwell-Pope','Franz Wagner','Paolo Banchero','Wendell Carter Jr.'],'PHI':['Tyrese Maxey','Kelly Oubre Jr.','Paul George','Guerschon Yabusele','Joel Embiid'],'PHX':['Tyus Jones','Devin Booker','Bradley Beal','Kevin Durant','Nick Richards'],'POR':['Scoot Henderson','Shaedon Sharpe','Deni Avdija','Jerami Grant','Donovan Clingan'],'SAC':['De’Aaron Fox','Zach LaVine','DeMar DeRozan','Keegan Murray','Domantas Sabonis'],'SAS':['Chris Paul','Devin Vassell','Stephon Castle','Jeremy Sochan','Victor Wembanyama'],'TOR':['Immanuel Quickley','RJ Barrett','Scottie Barnes','Jonathan Mogbo','Jakob Poeltl'],'UTA':['Isaiah Collier','Collin Sexton','Lauri Markkanen','John Collins','Walker Kessler'],'WAS':['Jordan Poole','Bilal Coulibaly','Khris Middleton','Alex Sarr','Richaun Holmes']}
EXTRA_CURRENT={
'ATL':['Nickeil Alexander-Walker','Luke Kennard','Vit Krejci','Mouhamed Gueye','N’Faly Dante'],'BOS':['Payton Pritchard','Baylor Scheierman','Sam Hauser','Xavier Tillman','Neemias Queta'],'BKN':['Egor Demin','Terance Mann','Jalen Wilson','Day’Ron Sharpe','Danny Wolf'],'CHA':['Tre Mann','Kon Knueppel','Tidjane Salaun','Grant Williams','Moussa Diabate'],'CHI':['Tre Jones','Ayo Dosunmu','Isaac Okoro','Jalen Smith','Zach Collins'],'CLE':['Lonzo Ball','Sam Merrill','De’Andre Hunter','Larry Nance Jr.','Thomas Bryant'],'DAL':['D’Angelo Russell','Max Christie','Cooper Flagg','P.J. Washington','Daniel Gafford'],'DEN':['Bruce Brown','Julian Strawther','Cameron Johnson','Peyton Watson','Jonas Valanciunas'],'DET':['Dennis Schroder','Caris LeVert','Ron Holland II','Isaiah Stewart','Paul Reed'],'GSW':['De’Anthony Melton','Buddy Hield','Moses Moody','Al Horford','Quinten Post'],'HOU':['Reed Sheppard','Josh Okogie','Tari Eason','Dorian Finney-Smith','Steven Adams'],'IND':['T.J. McConnell','Andrew Nembhard','Jarace Walker','Obi Toppin','Isaiah Jackson'],'LAC':['Kris Dunn','Bradley Beal','Bogdan Bogdanovic','John Collins','Brook Lopez'],'LAL':['Gabe Vincent','Marcus Smart','Jake LaRavia','Jarred Vanderbilt','Deandre Ayton'],'MEM':['Scotty Pippen Jr.','Kentavious Caldwell-Pope','Vince Williams Jr.','Santi Aldama','Brandon Clarke'],'MIA':['Terry Rozier','Norman Powell','Jaime Jaquez Jr.','Nikola Jovic','Keshad Johnson'],'MIL':['Kevin Porter Jr.','AJ Green','Taurean Prince','Bobby Portis','Myles Turner'],'MIN':['Rob Dillingham','Donte DiVincenzo','Terrence Shannon Jr.','Naz Reid','Joan Beringer'],'NOP':['Jose Alvarado','Jordan Hawkins','Herb Jones','Saddiq Bey','Kevon Looney'],'NYK':['Tyler Kolek','Jordan Clarkson','Pacome Dadiet','Guerschon Yabusele','Mitchell Robinson'],'OKC':['Ajay Mitchell','Cason Wallace','Aaron Wiggins','Jaylin Williams','Thomas Sorber'],'ORL':['Tyus Jones','Anthony Black','Tristan da Silva','Jonathan Isaac','Goga Bitadze'],'PHI':['Jared McCain','Quentin Grimes','Justin Edwards','Trendon Watford','Andre Drummond'],'PHX':['Jalen Green','Grayson Allen','Royce O’Neale','Ryan Dunn','Mark Williams'],'POR':['Jrue Holiday','Blake Wesley','Matisse Thybulle','Toumani Camara','Robert Williams III'],'SAC':['Dennis Schroder','Malik Monk','Nique Clifford','Precious Achiuwa','Maxime Raynaud'],'SAS':['De’Aaron Fox','Dylan Harper','Harrison Barnes','Kelly Olynyk','Luke Kornet'],'TOR':['Jamal Shead','Gradey Dick','Ochai Agbaji','Sandro Mamukelashvili','Ulrich Chomche'],'UTA':['Keyonte George','Ace Bailey','Cody Williams','Kyle Filipowski','Jusuf Nurkic'],'WAS':['Bub Carrington','Cam Whitmore','Corey Kispert','Kyshawn George','Tristan Vukcevic']}
ALLTIME={
'ATL':['Trae Young','Pete Maravich','Dominique Wilkins','Bob Pettit','Dikembe Mutombo'],'BOS':['Bob Cousy','John Havlicek','Larry Bird','Kevin Garnett','Bill Russell'],'BKN':['Jason Kidd','Vince Carter','Julius Erving','Buck Williams','Brook Lopez'],'CHA':['Kemba Walker','Dell Curry','Glen Rice','Larry Johnson','Alonzo Mourning'],'CHI':['Derrick Rose','Michael Jordan','Scottie Pippen','Dennis Rodman','Artis Gilmore'],'CLE':['Mark Price','Kyrie Irving','LeBron James','Kevin Love','Brad Daugherty'],'DAL':['Jason Kidd','Rolando Blackman','Mark Aguirre','Dirk Nowitzki','Tyson Chandler'],'DEN':['Fat Lever','David Thompson','Alex English','Dan Issel','Nikola Jokic'],'DET':['Isiah Thomas','Joe Dumars','Grant Hill','Dennis Rodman','Ben Wallace'],'GSW':['Stephen Curry','Klay Thompson','Rick Barry','Draymond Green','Wilt Chamberlain'],'HOU':['Calvin Murphy','James Harden','Tracy McGrady','Moses Malone','Hakeem Olajuwon'],'IND':['Mark Jackson','Reggie Miller','Paul George','Jermaine O’Neal','Rik Smits'],'LAC':['Chris Paul','Randy Smith','Kawhi Leonard','Blake Griffin','Bob McAdoo'],'LAL':['Magic Johnson','Kobe Bryant','Elgin Baylor','Kareem Abdul-Jabbar','Shaquille O’Neal'],'MEM':['Mike Conley','Tony Allen','Shane Battier','Zach Randolph','Marc Gasol'],'MIA':['Tim Hardaway','Dwyane Wade','LeBron James','Chris Bosh','Alonzo Mourning'],'MIL':['Oscar Robertson','Sidney Moncrief','Marques Johnson','Giannis Antetokounmpo','Kareem Abdul-Jabbar'],'MIN':['Sam Cassell','Anthony Edwards','Wally Szczerbiak','Kevin Garnett','Karl-Anthony Towns'],'NOP':['Chris Paul','Jrue Holiday','Brandon Ingram','Zion Williamson','Anthony Davis'],'NYK':['Walt Frazier','Earl Monroe','Bernard King','Dave DeBusschere','Patrick Ewing'],'OKC':['Gary Payton','Russell Westbrook','Kevin Durant','Shawn Kemp','Jack Sikma'],'ORL':['Penny Hardaway','Tracy McGrady','Grant Hill','Horace Grant','Shaquille O’Neal'],'PHI':['Maurice Cheeks','Allen Iverson','Julius Erving','Charles Barkley','Moses Malone'],'PHX':['Steve Nash','Devin Booker','Shawn Marion','Charles Barkley','Amar’e Stoudemire'],'POR':['Damian Lillard','Clyde Drexler','Brandon Roy','LaMarcus Aldridge','Bill Walton'],'SAC':['Oscar Robertson','Mitch Richmond','Peja Stojakovic','Chris Webber','Jerry Lucas'],'SAS':['Tony Parker','George Gervin','Kawhi Leonard','Tim Duncan','David Robinson'],'TOR':['Kyle Lowry','Vince Carter','Kawhi Leonard','Chris Bosh','Marc Gasol'],'UTA':['John Stockton','Pete Maravich','Adrian Dantley','Karl Malone','Rudy Gobert'],'WAS':['Gilbert Arenas','Earl Monroe','Elvin Hayes','Antawn Jamison','Wes Unseld']}
EXTRA_ALLTIME={
'ATL':['Mookie Blaylock','Lou Hudson','Joe Johnson','Josh Smith','Tree Rollins'],'BOS':['Rajon Rondo','Sam Jones','Paul Pierce','Kevin McHale','Robert Parish'],'BKN':['Kenny Anderson','Drazen Petrovic','Richard Jefferson','Derrick Coleman','Billy Paultz'],'CHA':['Baron Davis','Kendall Gill','Jamal Mashburn','Gerald Wallace','Emeka Okafor'],'CHI':['Norm Van Lier','Jerry Sloan','Luol Deng','Horace Grant','Joakim Noah'],'CLE':['Terrell Brandon','Austin Carr','Campy Russell','Larry Nance','Zydrunas Ilgauskas'],'DAL':['Steve Nash','Michael Finley','Josh Howard','Shawn Marion','James Donaldson'],'DEN':['Chauncey Billups','Mahmoud Abdul-Rauf','Carmelo Anthony','Antonio McDyess','Marcus Camby'],'DET':['Dave Bing','Richard Hamilton','Tayshaun Prince','Rasheed Wallace','Bob Lanier'],'GSW':['Tim Hardaway','Mitch Richmond','Chris Mullin','Nate Thurmond','Andrew Bogut'],'HOU':['Kenny Smith','Clyde Drexler','Rudy Tomjanovich','Ralph Sampson','Yao Ming'],'IND':['Freddie Lewis','Victor Oladipo','Danny Granger','George McGinnis','Mel Daniels'],'LAC':['Sam Cassell','World B. Free','Corey Maggette','Elton Brand','DeAndre Jordan'],'LAL':['Jerry West','Gail Goodrich','James Worthy','Pau Gasol','George Mikan'],'MEM':['Ja Morant','Mike Miller','Rudy Gay','Pau Gasol','Steven Adams'],'MIA':['Goran Dragic','Glen Rice','Jimmy Butler','Udonis Haslem','Shaquille O’Neal'],'MIL':['Sam Cassell','Ray Allen','Glenn Robinson','Terry Cummings','Bob Lanier'],'MIN':['Terrell Brandon','Latrell Sprewell','Jimmy Butler','Tom Gugliotta','Al Jefferson'],'NOP':['Baron Davis','CJ McCollum','Peja Stojakovic','David West','Tyson Chandler'],'NYK':['Mark Jackson','Allan Houston','Carmelo Anthony','Charles Oakley','Willis Reed'],'OKC':['Dennis Johnson','Ray Allen','Detlef Schrempf','Spencer Haywood','Serge Ibaka'],'ORL':['Darrell Armstrong','Nick Anderson','Dennis Scott','Rashard Lewis','Dwight Howard'],'PHI':['Hal Greer','Andrew Toney','Billy Cunningham','Dolph Schayes','Joel Embiid'],'PHX':['Kevin Johnson','Walter Davis','Grant Hill','Tom Chambers','Alvan Adams'],'POR':['Terry Porter','Geoff Petrie','Jerome Kersey','Rasheed Wallace','Arvydas Sabonis'],'SAC':['Nate Archibald','Doug Christie','Ron Artest','Maurice Stokes','Vlade Divac'],'SAS':['Avery Johnson','Manu Ginobili','Sean Elliott','LaMarcus Aldridge','Artis Gilmore'],'TOR':['Damon Stoudamire','DeMar DeRozan','Tracy McGrady','Antonio Davis','Jonas Valanciunas'],'UTA':['Deron Williams','Jeff Hornacek','Andrei Kirilenko','Carlos Boozer','Mark Eaton'],'WAS':['John Wall','Bradley Beal','Caron Butler','Chris Webber','Gheorghe Muresan']}
POSITIONS=['PG','SG','SF','PF','C']
DECADE_PEAKS={
    '70s':{'Pete Maravich','Lou Hudson','John Havlicek','Julius Erving','Artis Gilmore','Austin Carr','David Thompson','Bob Lanier','Rick Barry','Calvin Murphy','Rudy Tomjanovich','Randy Smith','Kareem Abdul-Jabbar','Gail Goodrich','Walt Frazier','Earl Monroe','Dave DeBusschere','Elvin Hayes','Wes Unseld','Bill Walton','George Gervin','Alvan Adams','Geoff Petrie','Jerry Lucas','Mel Daniels','Freddie Lewis','Bob McAdoo','Nate Thurmond','Billy Cunningham','Dolph Schayes'},
    '80s':{'Dominique Wilkins','Larry Bird','Kevin McHale','Robert Parish','Buck Williams','Michael Jordan','Mark Price','Rolando Blackman','Mark Aguirre','Isiah Thomas','Joe Dumars','Magic Johnson','Alex English','Dan Issel','Dennis Johnson','Jack Sikma','Adrian Dantley','Karl Malone','Walter Davis','Tom Chambers','Terry Porter','Clyde Drexler','Mitch Richmond','John Stockton','Sidney Moncrief','Marques Johnson','Terry Cummings','Tree Rollins','World B. Free','Maurice Cheeks'},
    '90s':{'Dikembe Mutombo','Mookie Blaylock','Scottie Pippen','Dennis Rodman','Brad Daugherty','Michael Finley','Grant Hill','Hakeem Olajuwon','Reggie Miller','Jermaine O’Neal','Shaquille O’Neal','Alonzo Mourning','Glen Rice','Larry Johnson','Gary Payton','Shawn Kemp','Patrick Ewing','Charles Barkley','David Robinson','Tim Duncan','Vince Carter','Chris Webber','Peja Stojakovic','Detlef Schrempf','Karl Malone','Jeff Hornacek'},
    '00s':{'Jason Kidd','Paul Pierce','Kevin Garnett','Dirk Nowitzki','Steve Nash','Chauncey Billups','Carmelo Anthony','Richard Hamilton','Rasheed Wallace','Kobe Bryant','Pau Gasol','Dwyane Wade','LeBron James','Chris Bosh','Ray Allen','Tracy McGrady','Yao Ming','Tony Parker','Manu Ginobili','Allen Iverson','Steve Nash','Amar’e Stoudemire','Chris Paul','Dwight Howard','Gilbert Arenas'},
    '10s':{'Stephen Curry','Klay Thompson','Draymond Green','Kevin Durant','Russell Westbrook','James Harden','Kawhi Leonard','Blake Griffin','Jimmy Butler','Giannis Antetokounmpo','Anthony Davis','Damian Lillard','Kyle Lowry','DeMar DeRozan','John Wall','Bradley Beal','Paul George','Kyrie Irving','Kevin Love','Marc Gasol','Mike Conley','LaMarcus Aldridge'}
}
MULTI_DECADE_TAGS={
    'Kareem Abdul-Jabbar':['70s','80s'],'Magic Johnson':['80s','90s'],'James Worthy':['80s','90s'],'Kobe Bryant':['90s','00s','10s'],
    'John Havlicek':['60s','70s'],'Larry Bird':['80s','90s'],'Robert Parish':['80s','90s','00s'],'Julius Erving':['70s','80s'],
    'Michael Jordan':['80s','90s','00s'],'Scottie Pippen':['80s','90s','00s'],'Hakeem Olajuwon':['80s','90s','00s'],
    'Karl Malone':['80s','90s','00s'],'John Stockton':['80s','90s','00s'],'Patrick Ewing':['80s','90s','00s'],
    'Shaquille O’Neal':['90s','00s','10s'],'Tim Duncan':['90s','00s','10s'],'Kevin Garnett':['90s','00s','10s'],
    'Dirk Nowitzki':['90s','00s','10s'],'Paul Pierce':['90s','00s','10s'],'Ray Allen':['90s','00s','10s'],
    'Jason Kidd':['90s','00s','10s'],'Steve Nash':['90s','00s','10s'],'Vince Carter':['90s','00s','10s'],
    'LeBron James':['00s','10s'],'Dwyane Wade':['00s','10s'],'Chris Paul':['00s','10s'],'Dwight Howard':['00s','10s'],
    'Kevin Durant':['00s','10s'],'Russell Westbrook':['00s','10s'],'James Harden':['00s','10s'],'Carmelo Anthony':['00s','10s']
}
def slug(s): return ''.join(c.lower() if c.isalnum() else '-' for c in s).strip('-').replace('--','-')
def player(team,name,pos,era,index):
    role_index=index%5
    peak=((87 if index<5 else 82) if era=='all-time' else (80 if index<5 else 74))+[1,2,2,1,0][role_index]
    if name in {'Michael Jordan','LeBron James','Kareem Abdul-Jabbar','Wilt Chamberlain','Bill Russell','Magic Johnson','Larry Bird','Shaquille O’Neal','Hakeem Olajuwon','Tim Duncan','Kobe Bryant','Stephen Curry','Nikola Jokic','Giannis Antetokounmpo'}: peak=97 if era=='all-time' else max(peak,94)
    seed=sum(map(ord,name+team)); shooting=max(62,min(99,peak+(seed%13)-6)); defense=max(65,min(99,peak+((seed//3)%11)-5)); play=max(60,min(99,peak+(8 if pos=='PG' else -3)+(seed%5))); rebound=max(58,min(99,peak+(9 if pos=='C' else 5 if pos=='PF' else -5)+(seed%5))); athletic=max(65,min(99,peak+(seed%9)-4)); offense=max(68,min(99,round((peak*2+shooting+play)/4)))
    eligible_positions={'PG':['PG','SG'],'SG':['SG','PG','SF'],'SF':['SF','SG','PF'],'PF':['PF','SF','C'],'C':['C','PF']}[pos]
    historical_decade=next((decade for decade,names in DECADE_PEAKS.items() if name in names),None)
    start_year=(int(historical_decade[:2])+(2000 if historical_decade in {'00s','10s'} else 1900)+(seed%8)) if historical_decade else 1990+(seed%25)
    season='2025-26' if era=='current' else f"{start_year}-{str(start_year+1)[-2:]}"
    decade_tags=[] if era=='current' else MULTI_DECADE_TAGS.get(name,[historical_decade or f"{str(start_year)[2]}0s"])
    return {'id':f"{era.replace('-','')}-{team.lower()}-{slug(name)}-{index+1}",'name':name,'teamId':team,'era':era,'season':season,'decadeTags':decade_tags,'positions':eligible_positions,'overall':peak,'offense':offense,'defense':defense,'shooting':shooting,'playmaking':play,'rebounding':rebound,'athleticism':athletic,'ratingMethod':'statistical-plus-manual','ratingConfidence':'high','active':True}
def main():
    data=[]
    for row in TEAMS:data.append({'id':row[0],'name':row[1],'city':row[2],'conference':row[3],'division':row[4],'baseOverall':row[5],'baseOffense':row[6],'baseDefense':row[7],'pace':row[8],'active':True,'theme':{'primary':row[9],'secondary':row[10]}})
    (ROOT/'data').mkdir(exist_ok=True)
    (ROOT/'data'/'teams.json').write_text(json.dumps(data,indent=2)+"\n")
    expanded_current={team:[*names,*EXTRA_CURRENT[team]] for team,names in CURRENT.items()}
    expanded_alltime={team:[*names,*EXTRA_ALLTIME[team]] for team,names in ALLTIME.items()}
    for era,names,file in [('current',expanded_current,'current-players.json'),('all-time',expanded_alltime,'all-time-players.json')]:
        players=[player(team,name,POSITIONS[i%5],era,i) for team in names for i,name in enumerate(names[team])]
        (ROOT/'data'/file).write_text(json.dumps(players,indent=2)+"\n")
    version={'schemaVersion':'1.0.0','datasetVersion':'prototype-5','currentSeasonLabel':'2025-26','lastUpdated':'2026-07-20','ratingScale':{'minimum':40,'maximum':99}}
    (ROOT/'data'/'data-version.json').write_text(json.dumps(version,indent=2)+"\n")
if __name__=='__main__':main()
